- type: job
  id: DeathSquad
  name: job-name-deathsquad
  description: job-description-deathsquad
  playTimeTracker: JobDeathSquad
  setPreference: false
  startingGear: DeathSquadGear
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand

- type: startingGear
  id: DeathSquadGear
  subGear:
  - BoxSurvivalEngineering
  - ERTPlasmamanGear # TODO: death squad envirosuit
  - GasTankSuitStorage
  equipment:
    jumpsuit: ClothingUniformJumpsuitDeathSquad
    back: ClothingBackpackDeathSquad
    mask: ClothingMaskGasDeathSquad
    eyes: ClothingEyesHudSecurity
    ears: ClothingHeadsetAltCentCom
    gloves: ClothingHandsGlovesSpecops
    outerClothing: ClothingOuterHardsuitDeathsquad
    shoes: ClothingShoesBootsMagAdv
    id: DeathsquadPDA
    pocket1: EnergyCutlassOverclocked
    pocket2: WeaponPistolAnaconda
    belt: ClothingBeltMilitaryWebbingMedFilled
  storage:
    back:
    - WeaponPulsePistol
    - PolyacidGasGrenade
    - PolyacidGasGrenade
    - MagazineCaselessRifleUranium
    - MagazineCaselessRifleUranium
    - C4
    - C4
    - C4
    - C4
    - JawsOfLife
    - WelderExperimental
    - BlueShieldShield
    - PortableRecharger
    - HandTeleporterAdmeme
    - BluespaceLifelineImplanter
    - FreedomImplanter
    - ScramImplanter
    - DoubleEmergencyOxygenTankFilled
    - DoubleEmergencyNitrogenTankFilled
    - DoubleEmergencyOxygenTankFilled
    - DoubleEmergencyNitrogenTankFilled
    - WeaponPulseRifle
  inhand:
  - WeaponRifleJackdaw
